### PR TITLE
Improve config file parsing.

### PR DESCRIPTION
**Pull request by feld**
Properly exit with an error and print if important conditions arise:

- Cannot read main config file
- Cannot read resources.cfg
- No log file defined in main config file

This was born out of the frustration of an accidental permisisons change
to resources.cfg and the pain required to track down why thousands of
Nagios checks suddenly started failing.

The poor sap who did a "restart" was confused when the system blew up
and nobody could identify what was happening until we dug into debug
logs and found that the macro parsing had gone awry.

Simply logging that resources.cfg is not readable is unacceptable. It
needs to be an obvious and showstopping error. Nagios should not attempt
to fly with one wing.

These changes will surely improve troubleshooting for admins everywhere.

### CODE REVIEW

**Comment by dlangille** [comment]
Yes please.

**Comment by feld** [comment]
An additional check to ensure you can successfully write to the location of the log file would be nice as well, but I did not attempt it. It may already exist in the logging code. I haven't had time to check.

**Comment by hedenface** [comment]
I like 66% of this - but I won't commit to liking the remainder until you walk me through the changes made in regards to the log_file section and your logic behind them!

Also - if you can change the branch to `maint` and add yourself to the contributors that would be fantastic.

**Comment by feld** [comment]
Ok, this is the logic of the log_file changes:

**a)** 

The logic of "if(daemon_mode == FALSE)" was nonsense. Why would you want it to only log an error if you're running nagios in the foreground? And where is it going to log this error to if log_file isn't defined? Assuming you were running with nagios printing all log data to stdout that might make sense because you can still see other errors/logs being printed to the screen, but this isn't how nagios works.

**b)**

`
if(!strcmp(log_file, "")) {
`

This didn't work. I don't know why. I tried to keep it, but it just wouldn't work. I don't know what the value of log_file was when it's not defined, but it wasn't "". So I had to concoct a bulletproof solution:

**c)** 

in the read_main_config_file function, let's start by defining log_file as NULL

`
char *log_file = NULL;
`

When we get to the very end of parsing the config file the last step is to make sure we have a usable log_file value. The first thing we do is make sure log_file is not NULL. If it is not, we can assume it's now safe to strip() log_file. I moved this to below the comparison because I did not want log_file to be altered in any way before the check against NULL. I did not track down what your strip() function does, but I can assume it's adding or removing spaces/tabs from before and after the string. I came to this conclusion by checking if strip() was a standard function provided by libc and it appears it is not.

I'm not a great C programmer by any means, but this seems to be safe, reliable, and should compile without warnings

**Comment by hedenface** [comment]
We had some internal conversation in regards to this - I think instead of using printf() we're going to continue using logit() since the users can specify if they want syslogging or not - also, the second paramter of logit() tells it to print to the screen.

Are you able to adjust it as such or would you prefer me to?

**Pull request merged**
