### PR TITLE
fix for duplicated flapping comments across Nagios reloads

### PR DESCRIPTION
**Pull request by c-jung**
Version 4.4.1 duplicates the flapping comments when reloading the Nagios process. This happens because the main process stores the current state to the retention data file, reinitializes by reading the previously safed retention data and then recheck the flapping state of all hosts and services (this is only done with large installation tweaks disabled).
Rechecking for flapping hosts and services leads to an new flapping comment. This overwrites the flapping_comment_id of the host or service object and breaks the link between the object and its comment.
The old flapping comment is not deleted.
The changes of this pull request store the flapping_comment_id to the retention data file (to keep the link between the object and the flapping comment) and prevent the creation of a new flapping comment if there is already one.

### CODE REVIEW

**Comment by hedenface** [comment]
I believe this has already been fixed in maint. Can you verify?

**Comment by hedenface** [comment]
Okay. Thank you, then.

Will you change the base branch to maint, please?

**Comment by c-jung** [comment]
I've changed the base branch of this pull request to maint.

**Comment by hedenface** [comment]
Can you add an additional PR adding this to the Changelog for 4.4.2 and yourself to the THANKS file?

**Pull request merged**
