### PR TITLE
Set the document title to the hostname of the web server nagios runs on.

### PR DESCRIPTION
**Pull request by leres**
I have six instances of nagios running between work and personal projects and it is generally helpful to have the title set to the hostname. This sets title to the 'Nagios: ' and the hostname.

### CODE REVIEW

**Comment by hedenface** [comment]
Not sure I like the idea of this being done in javascript (for a few reasons). Can you edit it to use a few `<?php ?>` tags and the `$_SERVER['SERVER_NAME']` variable responsible? This way it's the real name, and not just want the client sees as the name.

Please also add your changes to the Changelog. Thanks!

**Comment by leres** [comment]
I've been working with nagios 3.5.1 because that's what the FreeBSD port uses but I see the master version is vastly different; for example here's how I believe the title now gets set:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">

<html>
<head>
        <meta name="ROBOTS" content="NOINDEX, NOFOLLOW">
<script LANGUAGE="javascript">
        var n = Math.round(Math.random() * 10000000000);
        document.write("<title>Nagios Core on " + window.location.hostname + "</title>");
        document.cookie = "NagFormId=" + n.toString(16);
</script>
```
So I'm not sure if there is anything to do. Although I do agree with you that using php instead of javascript is better (and "Nagios Core on " is long enough to cause the hostname to be truncated  depending on your window manager -- it's too long in my case).

**Comment by hedenface** [comment]
It might be too long because of your window manager, or even your browser. But, generally when hovering over a tab or equivalent, you do see the entire title. And In some cases it shows up in the application's *actual* title bar.

I don't think there isn't anything to do. Find the appropriate `<title></title>` lines, and simply add `<?php echo $__SERVER['SERVER_NAME']; ?>` where it needs to be.

Test it, and then update your PR. As @ericloyd said, download source for version 4.

Let me know if you aren't willing to do this, so I can close the PR - and I'll make the change myself.

**Comment by leres** [comment]
nagios 4 creates the main html content dynamically using javascript:
`document.write("<title>Nagios Core on " + window.location.hostname + "</title>");`
So the change I would make would be to change "<title>Nagios Core on "  to "<title>Nagios: " so it doesn't get truncated (see attached):

nagios

**Comment by hedenface** [comment]
Eh. I'll merge, so you get the sweet internet points - but I'm going to overwrite it with php almost immediately. Thank you.

**Comment by hedenface** [comment]
Wait. Why didn't you just update the original javascript that does the `document.write()` ? Am I missing something?

**Pull request merged**
