### PR TITLE
Enhancement #687: Allow Multi-line Comments

### PR DESCRIPTION
**Pull request by iwhite-nagios**
This changeset takes the character '\n' and replaces it with "\<br\>" so the comment presents in desired format and avoids assigning new commits via the nagios command queue. Also some minor performance/semantic fixes.

### CODE REVIEW

**Comment by iwhite-nagios** [comment]
image
Here is an example of the new note display,

**Comment by iwhite-nagios** [comment]
image
Before entering text.
image
After entering some text.

**Comment by sawolf** [comment]
Nice! I haven't run this code yet, but does this also work if you leave a comment via external command?
(documentation [here](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/extcommands.html) and [here](https://assets.nagios.com/downloads/nagioscore/docs/externalcmds/cmdinfo.php?command_id=1))

**Comment by sawolf** [comment]
Spoke internally with @iwhite-nagios - tags do work on the command line. Still need to verify that XSS doesn't work.

**Comment by iwhite-nagios** [comment]
@sawolf The command line allows for tags, including <script>, to get through, so javascript can be run on the page. We could do a check when we are displaying the message to remove tags except "<br>, but that would not be a part of this Enhancement. The User Interface removes all angle braces "<>", so tags cannot get through that endpoint.

**Pull request merged**
