### PR TITLE
Support for customizing side.php with quicklinks

### PR DESCRIPTION
**Pull request by xavierba**
This PR implements the change suggested by my colleague in #493.

### CODE REVIEW

**Comment by xavierba** [comment]
As the sitelinks.php file is effectively located in $CFGDIR and just symlinked from $HTMLDIR, it is safe from upgrade for people using a distribution packaged Nagios, as it will be marked as a config file and thus preserved upon upgrade. However, you are indeed right, it is not safe from a source distribution standpoint. I'll look at how to fix that, I would expect to find the same kind of security belt for config.inc.php.
Speaking of config.inc.php, would you accept a patch that does the same symlink from $HTMLDIR to $CFGDIR trick for it, as I did for quicklinks.php ?

**Comment by hedenface** [comment]
I think in order to preserve the quicklinks.php between upgrades it should likely be moved to it's own `install-quicklinks` make target. And then that target should be included in all the places where the lists appear (in plain `make` for example, and after a normal `make install` happens). The target should be linked in `make fullinstall` as well.

I don't think a change like that for config.inc.php should happen in between major versions, personally. Not that I haven't pushed breaking changes, but I can see that being a recipe for disaster when someone goes to upgrade from 4.3 to 4.4.

You're welcome to make that change against the `nv5dev` branch, however.

**Comment by xavierba** [comment]
Would this additional commit be enough ?

**Comment by hedenface** [comment]
Yes that should be fine. I'm going to add it to a 4.5 branch.

**Comment by hedenface** [comment]
Can you change the branch to `nagios-4.5.0` and add your changes to the enhancements list for 4.5.0 in the changelog, and add yourself to the thanks file as well.

**Comment by xavierba** [comment]
Rebased to nagios-4.5.0

**Comment by hedenface** [comment]
Thanks!

**Pull request merged**
