### PR TITLE
Fix memory leak when call free(subscr).

### PR DESCRIPTION
**Pull request by ggvl**
strdup will alloc some memory, and it should be freed when call free(subscr).

### CODE REVIEW

**Comment by ggvl** [comment]
@ozamosi is this OK?

**Comment by ggvl** [comment]
@catharsis

**Comment by ggvl** [comment]
@moschlar

**Comment by ggvl** [comment]
@mjtrangoni

**Comment by ggvl** [comment]
@ozamosi  can you review the code?

**Comment by sawolf** [comment]
Hi @ggvl, thanks for the patch. The change looks good to me.

In the future, please refrain from harassing random contributors - only people in the NagiosEnterprises organization (https://github.com/NagiosEnterprises) will be able to merge patches.

**Pull request merged**
