### PR TITLE
Syntax needed for php 7+.  Solution provided by   ZAFRAN ULLAH 

### PR DESCRIPTION
**Pull request by tjyang**
- This is on RockyLinux 8 with php8, Here is the [ fix details]( https://itpro.com.pk/2022/09/29/nagios-trying-to-access-array-offset-on-value-of-type-bool/).
```
[me@nagios01 ~]$ php -v
PHP 8.0.27 (cli) (built: Jan  3 2023 16:17:26) ( NTS gcc x86_64 )
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.27, Copyright (c), by Zend Technologies
[me@nagios01 ~]$ sudo systemctl status -l httpd
<snipped>
May 17 06:41:57 nagios01 php[22081]: PHP Stack trace:
May 17 06:41:57 nagios01 php[22081]: PHP   1. {main}() /usr/share/nagios/html/side.php:0
May 17 06:41:57 nagios01 php[22081]: PHP   2. include_once() /usr/share/nagios/html/side.php:2
May 17 06:41:57 nagios01 php[22081]: PHP   3. get_enable_page_tour() /usr/share/nagios/html/includes/utils.inc.php:12
May 17 06:41:57 nagios01 php[22081]: PHP   4. read_cgi_config_file($thefile = *uninitialized*) /usr/share/nagios/html/includes/utils.inc.php:10
May 17 06:41:57 nagios01 php[51443]: PHP Warning:  Trying to access array offset on value of type bool in /usr/share/nagios/html/includes/utils.inc.php on line 154
May 17 06:41:57 nagios01 php[51443]: PHP Stack trace:
May 17 06:41:57 nagios01 php[51443]: PHP   1. {main}() /usr/share/nagios/html/main.php:0
May 17 06:41:57 nagios01 php[51443]: PHP   2. get_update_information() /usr/share/nagios/html/main.php:128
May 17 06:41:57 nagios01 php[51443]: PHP   3. read_main_config_file($thefile = '') /usr/share/nagios/html/includes/utils.inc.php:35
[me@nagios01 ~]$
```

### CODE REVIEW

**Comment by dougnazar** [comment]
See commit a863966bc8bbb5de56553304080c5bd26178495d which already fixes `read_main_config_file()` & `read_cgi_config_file()`. I didn't notice the other locations, they don't warn on my setup, however it looks like the could be fixed in a similar way.

**Comment by tjyang** [comment]
> See commit [a863966](https://github.com/NagiosEnterprises/nagioscore/commit/a863966bc8bbb5de56553304080c5bd26178495d) which already fixes `read_main_config_file()` & `read_cgi_config_file()`. I didn't notice the other locations, they don't warn on my setup, however it looks like they could be fixed in a similar way.
> 
> Edit: Ah, I see they only read the first 50 lines before exiting. Still they should be fixed.
@dougnazar , thanks for the comment.
I am running Nagioscore  rpm from EPEL8 on RL8. With following config in /etc/php.ini
the php warning/error should recorded in syslog. 
```
[me@nagios01 servers]$ egrep "^error_reporting|^error_log"  /etc/php.ini
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
error_log = syslog
[me@nagios01 servers]$
```

**Comment by dougnazar** [comment]
From a quick Google, it looks like [EPEL8](https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/n/) is running version 4.4.9 and that patch was released in 4.4.11.

**Comment by sawolf** [comment]
Thanks for the patch!

**Pull request merged**
