### PR TITLE
Various fixes and cleanups

### PR DESCRIPTION
**Pull request by knweiss**
Check out the individual commit msgs for details.

Please review. Warning: This is only compile-tested.

Feel free to cherry-pick.

### CODE REVIEW

**Comment by hedenface** [comment]
As reviewing, I'll be leaving notes here.

What was the memory leak from the error_string in cgi/cmds.c. Am I missing some return before it's freed that stops it from happening? Is there some way I can recreate the leak?

**Comment by hedenface** [comment]
The change in command.c for moving 'finding the object sooner' will cause a memory leak by placing it in that order. Additional memory must be freed in the `return ERROR` blocks.

**Comment by hedenface** [comment]
Heh. That was literally the next commit :)

**Comment by knweiss** [comment]
@hedenface In the original code `error_string` was always strdup()ed. Then, at the end of the function, there was this code using `error_string`:
```c
        /* some error occurred (data was probably missing) */
        else if(error_string) {
                if(content_type == WML_CONTENT)
                        printf("<p>%s</p>\n", error_string);
                else {
                        printf("<P><DIV CLASS='errorMessage'>%s</DIV></P>\n", error_string);
                        free(error_string);
```
In the `WML_CONTENT` case there was no `free(error_string)`.

**Comment by hedenface** [comment]
Ah, I see. I think instead of removing all the strdups, we'll just add a free there. I'll be pulling these in shortly - still reviewing - thank you.

**Pull request merged**
