### PR TITLE
Add host_down_disable_service_checks directive to nagios.cfg

### PR DESCRIPTION
**Pull request by tmcnag**
Adding the option to disable checks on services if the associated host is in a non-UP state.  Uses the same logic as active check enabled/disabled, time period valid, and dependencies in OK states.

### CODE REVIEW

**Comment by willemdh** [comment]
+1

**Comment by tmcnag** [comment]
I am considering extending the behavior, but I want to be careful with this.  I am thinking of setting the option like so:

host_down_set_service_state=u/w/c/o/n

One option would be set.  Selecting "n" (null, nothing) would be the same behavior that I am requesting be pulled - the service state and output remains the same, the check is not performed but is rescheduled.

Selecting one of u/w/c/o would set the state to UNKNOWN / WARNING / CRITICAL / OK and set the output to "Host is down!" or something.  The output would in all likelihood not be user-configurable in nagios.cfg.  This is cool and all, but has the downside of not reducing the load as much as just not running the check (and reducing the load was the whole reason for this patch in the first place).

Thoughts?

**Comment by scottwilkerson** [comment]
I assigned estanley375 to the issue to have a look to see if there are other things to be considered.  @BanditBBS, if you get some results after you roll out we would appreciate the feedback.  Thanks!

**Comment by box293** [comment]
I think this is a great feature add. I like the simplicity of it however it may be too broad of a setting. I was thinking perhaps a directive per service or host that allows you to ignore the directive in nagios.cfg. This way you can have the global setting enabled to apply to 99% of hosts but for the other 1% where you may want the traditional behavior it could still be enabled. This in turn still achieves the goal of reducing load.

**Comment by tmcnag** [comment]
You mean like a dependency?  ;)

The point of this feature request was to make it broad.  Adding in a per-object override is complicated, since then we need to check if (host_down_disable_service_checks==1 && wait_just_kidding_ignore_host_down_disable_service_checks_setting_for_this_host==1).  If we were going to do that, we could just scrap the whole patch and go back to using dependencies.

**Comment by BanditBBS** [comment]
Actually, Troy's suggesting is good for the case where one out of 2000
hosts needs to ignore the setting.  However, just getting this patch as is,
is hands down an awesome addition.  I'll find another way to work around
for the 1 out of 2000 hosts that doesn't need it.

Scott, I am going away from office and then on vacation soon, so probably
won't put into production until June 29th.  I wouldn't want to now, just in
case something does go wrong.  But seriously appreciate assigning a dev to
take a look!

**Comment by tmcnag** [comment]
The problem with adding another config directive is that we now need to update the XI CCM, the databases, the interface...  That's not something I can easily do  :)

I like the concept, but that would be out of my hands.

**Comment by scottwilkerson** [comment]
I'm with Trevor on this, the one off, or mix/match can be accomplished using dependencies or event handlers, whereas this addition if more of a broad stroke.  Additionally, adding object config items requires modifications for addon modules and at best would have to wait for a major release, require a bunch of work for others who have created addon modules for Core.

**Pull request merged**
