### PR TITLE
Bug #617 : limit make {clean|rpm} in Makefile to react to CentOS/RHEL…

### PR DESCRIPTION
**Pull request by tjyang**
as title stated.

### CODE REVIEW

**Comment by Madlohe** [comment]
Hi @tjyang,

Thanks for the PR. I'll test/review this tommorow

**Comment by Madlohe** [comment]
Okay, this mostly looks good, just one issue for me:

On your system, does `rm -rf *.rpm` fail if you don't match any files? On every system I've used, the output will be similar to the following:
```
# rm -rf *.rpm
# echo $?
0
```
If this happens for you as well, I'd rather keep the rpmclean command within the regular clean (maybe have clean call rpmclean). This way, `make clean` will return the system to the state it was in after `./configure`.

**Comment by tjyang** [comment]
Hi @Madlohe 

I removed rpmclean target in contrib/Makefile.in  to minimize the change scope.  rpm builder will need to run "rm *.rpm" personally.  Existing *.rpm will be overwritten when "make rpm" got run again. so no need to clean rpm when doing "make rpm" in contrib dir.

let me know if you still want to keep "cd contrib;make rpmclean". 

May be in another PR we can explore "make rpm" and "make clean" at nagioscore level.
But I think this will cause many other changes. 
```
[me@nagios02t nagioscore]$ make
Please supply a command line argument (i.e. 'make all').  Other targets are:
   nagios cgis contrib modules workers
   test
   install                          install-base
   install-cgis                     install-html
   install-webconf                  install-config
   install-init                     install-daemoninit
   install-commandmode              install-groups-users
   install-exfoliation              install-classicui
   install-basic                    install-unstripped
   fullinstall
   clean
[me@nagios02t nagioscore]$

```

**Comment by Madlohe** [comment]
I committed the line I was concerned about. I'm just waiting on travis to verify that the build still works and then I'll merge this.

**Pull request merged**
